name: "Delete corresponding App on branch delete"

on:
  delete:
  workflow_dispatch:

jobs:
  delete:
    environment:
      name: dev

    runs-on: ubuntu-latest
    name: Deleting App
    steps:
      - name: Fetch Repo
        uses: actions/checkout@v2
      - name: Branch Deleted
        run: echo "${{ github.event.ref }}"
      - name: Default Branch
        run: echo "${{ github.event.repository.default_branch }}"
      - name: Download art
        run: curl --silent https://github.com/argonautdev/public/releases/latest/download/art-linux -L -o art
      - name: Configure art
        run: |
          chmod +x ./art
          sudo mv ./art /usr/local/bin/art
          art configure --key ${{ secrets.ART_KEY }} --secret ${{ secrets.ART_SECRET }}
          art app delete -f .art/argonaut-dev-demo.yaml --set appName=${{ (github.event.ref == github.event.repository.default_branch) && 'demo' || format('{0}-{1}', 'demo', github.event.ref) }}
